---
- debug:
    var: yunohost_apps_nextcloud.config.apps.keys()
  when: yunohost_apps_nextcloud.config.apps is defined
  tags:
    - debug

- name: "Combine args for each apps"
  set_fact: 
    yunohost_nc_apps_settings:
      "{{
        yunohost_nc_apps_settings | default([]) +
        [ {'name': item, 'args': yunohost_apps_nextcloud.config.apps[item].keys() | list} ] 
      }}"
  loop: "{{ yunohost_apps_nextcloud.config.apps.keys() }}"

- debug:
        var: yunohost_nc_apps_settings

- name: Set NextCloud modules apps config
  command: >- 
          php occ config:app:set "{{ item.0.name }}" "{{ item.1 }}"
          --value "{{ yunohost_apps_nextcloud.config.apps[item.0.name][item.1] }}"
  loop: "{{ yunohost_nc_apps_settings | subelements('args') }}"
